name: CI

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:

jobs:
  test:
    name: Test (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.9', '3.10', '3.11', '3.12' ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Build sdist and wheel
        run: |
          python -m pip install build
          python -m build
      - name: Verify CSVs are packaged in wheel
        run: |
          python - << 'PY'
          import glob, zipfile, sys
          wheel = sorted(glob.glob('dist/*.whl'))[-1]
          required = [
              'cargos_api/data/luoghi.csv',
              'cargos_api/data/tipo_documento.csv',
              'cargos_api/data/tipo_pagamento.csv',
              'cargos_api/data/tipo_veicolo.csv',
          ]
          with zipfile.ZipFile(wheel) as zf:
              names = set(zf.namelist())
          missing = [p for p in required if not any(n.endswith(p) for n in names)]
          if missing:
              print('Missing package data:', missing)
              sys.exit(1)
          print('OK: all CSVs present in', wheel)
          PY

  publish:
    name: Publish to PyPI
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [ test ]
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # for trusted publishing (if enabled on PyPI) or ignored when using API token
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build sdist and wheel
        run: |
          python -m pip install --upgrade pip build
          python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

